$fn=50;

// bottom of plunger where it engages with the loadcell
LOWER_HOLE_DIAMETER=10;
LOWER_LENGTH=13;

SPRING_REST_HEIGHT=6;

SPRING_OUTER_DIAMETER=23.5;
SPRING_INNER_DIAMETER=18.5;


UPPER_LENGTH=28;

cylinder(d=LOWER_HOLE_DIAMETER, h=LOWER_LENGTH);

translate([0, 0, LOWER_LENGTH])
cylinder(d=SPRING_OUTER_DIAMETER, h=SPRING_REST_HEIGHT);

translate([0, 0, LOWER_LENGTH + SPRING_REST_HEIGHT])
cylinder(d=SPRING_INNER_DIAMETER, h=UPPER_LENGTH);

